name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'  # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --base . --verbose --no-progress './*.rst' './*.ipynb'
          format: markdown
          output: /tmp/result.md
          fail: true